# Generated by Django 2.1.3 on 2018-11-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181109_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Driver', 'Driver')], default='Driver', max_length=32),
            preserve_default=False,
        ),
    ]
